### ISSUE TITLE
Open positions for Cetner for Health AI

### ISSUE THREAD

**Issue by AudreyWen** [CUHealthAI/website#1]
please post below on AI website:

Req 22025 - Grant Specialist Position
https://cu.taleo.net/careersection/2/jobdetail.ftl?job=22025&lang=en

Req 22018 - Communication and Engagement Specialist Position
https://cu.taleo.net/careersection/2/jobdetail.ftl?job=22018&lang=en

Req 21772 - Scientific/Medical Writer / Open Rank Instructor Position
https://cu.taleo.net/careersection/2/jobdetail.ftl?job=21772&lang=en

**Comment by vincerubinetti** [comment]
This has been added at https://medschool.cuanschutz.edu/ai/join
