### ISSUE TITLE
Event - Mapping and Navigating the Human Regulatory Genome

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#10]
Topic: Wouter Meuleman - Seminar - Mapping and Navigating the Human Regulatory Genome
Time: Aug 12, 2021 12:00 AM Mountain Time (US and Canada)
Join Zoom Meeting
https://ucdenver.zoom.us/j/93822821918 (edited) 

![title_slide_Meuleman](https://user-images.githubusercontent.com/87993502/128220967-3f4e94a5-c9ad-4992-bdfc-624e67713ef9.png)

**Comment by vincerubinetti** [comment]
@fiandram I'm assuming the time is supposed to be 12 PM not AM. 

Updated at https://medschool.cuanschutz.edu/ai/events

**Comment by fiandram** [comment]
Oops @vincerubinetti !  You got it! Thanks!!
