### ISSUE TITLE
Wenbin Zhang, PhD

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#13]
### Title

Learning Fairness and Graph Deep Generation in Dynamic Environments

### Host

Wenbin Zhang, PhD

### Start date and time

08/26/2021 12:00 PM

### End date and time

08/26/2021 1:00PM

### Link

https://ucdenver.zoom.us/j/95958677230

### Image

[slides.pdf](https://github.com/CUHealthAI/website/files/6994221/slides.pdf)

**Comment by vincerubinetti** [comment]
implemented: https://medschool.cuanschutz.edu/ai/events

**Comment by fiandram** [comment]
Link to Wenbin Zhang Seminar
https://youtu.be/KPJ1WM9wL5Y

**Comment by vincerubinetti** [comment]
updated at https://medschool.cuanschutz.edu/ai/media
