### ISSUE TITLE
Wouter Meuleman, PhD

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#14]
### Title

Mapping and Navigating the Human Regulatory Genome

### Host

Wouter Meuleman , PhD - Principal Investigator, Head of Cell Science Lab - Altius Institute for Biomedical Sciences, Seattle, WA

### Start date and time

8/12/2021 12:00PM

### End date and time

8/12/2021 1:00PM

### Link

 https://www.youtube.com/watch?v=Wkf339-v_4M

### Image

This is the you tube link for the seminar that occurred on 8/12

**Comment by vincerubinetti** [comment]
implemented: https://medschool.cuanschutz.edu/ai/media
