### ISSUE TITLE
REMOVE -Gamze Gursoy

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#15]
### Title

Genetic Privacy in the Age of Multiomics

### Host

Gamze Gursoy

### Start date and time

N/A

### End date and time

N/A

### Image

Gamze has asked us to remove her video.  It has been taken off of YouTube so we can also remove it on the website.

**Comment by vincerubinetti** [comment]
removed https://medschool.cuanschutz.edu/ai/media
