### ISSUE TITLE
Da Ma, PhD - AI Engineering for Medical Image Analysis

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#16]
### Title

AI Engineering for Medical Image Analysis

### Host

Da Ma, PhD

### Start date and time

09/02/21 12:00PM

### End date and time

09/02/21 1:00PM

### Link

https://ucdenver.zoom.us/j/92815758521

### Image

[Colorado_Da_Ma_Seminar_Talk_First_Slide.pptx](https://github.com/CUHealthAI/website/files/7001949/Colorado_Da_Ma_Seminar_Talk_First_Slide.pptx)

**Comment by vincerubinetti** [comment]
added https://medschool.cuanschutz.edu/ai/events

**Comment by fiandram** [comment]
Link to Da Ma Seminar:
https://www.youtube.com/watch?v=fY3A0sd5D_w

**Comment by vincerubinetti** [comment]
updated at https://medschool.cuanschutz.edu/ai/media
