### ISSUE TITLE
Arjun Krishnan, PhD - Tackling Incomplete Data, Unstructured Metadata, and Hidden Curricula

### ISSUE THREAD

**Issue by fiandram** [CUHealthAI/website#17]
### Title

Tackling Incomplete Data, Unstructured Metadata, and Hidden Curricula

### Host

Arjun Krishnan, PhD

### Start date and time

10/7/2021 12:00PM

### End date and time

10/7/2021 1:00PM

### Link

https://ucdenver.zoom.us/j/98853229126?from=addon

### Image

[Krishnan_Title-slide.pdf](https://github.com/CUHealthAI/website/files/7219585/Krishnan_Title-slide.pdf)

**Comment by vincerubinetti** [comment]
Added https://medschool.cuanschutz.edu/ai/events
