### ISSUE TITLE
Creating a Admin / Operation & IT team on AI Website

### ISSUE THREAD

**Issue by AudreyWen** [CUHealthAI/website#2]
Few examples:

Department of Surgery:
https://medschool.cuanschutz.edu/surgery/divisions-centers-affiliates/vascular/our-team

Department of EM
https://medschool.cuanschutz.edu/emergency-medicine/about-us/faculty-staff/staff

Cancer Center
https://medschool.cuanschutz.edu/colorado-cancer-center/about-us/cu-cancer-center-staff

**Comment by vincerubinetti** [comment]
Rearranged the site today. Center-wide team members will be added to this page: https://medschool.cuanschutz.edu/ai/team

Will close this issue once I get the appropriate profile pictures and information from people.

**Comment by vincerubinetti** [comment]
https://medschool.cuanschutz.edu/ai/team
