### ISSUE TITLE
Carlos Rodriguez headshot for team page

### ISSUE THREAD

**Issue by ceero1980** [CUHealthAI/website#6]
![Carlos Rodriguez Headshot](https://user-images.githubusercontent.com/87772764/126526568-0069e5a2-288e-49a4-b8bd-8c468fb344a3.jpg)

Business Operations Manager
carlos.rodriguez@cuanschutz.edu

**Comment by vincerubinetti** [comment]
Added: https://medschool.cuanschutz.edu/ai/team
